### ISSUE TITLE
Can I use multiple tags on one build?

### ISSUE THREAD

**Issue by onnimonni** [drone-plugins/drone-ecr#25]
Hey!

My usecase is following:
We have staging servers and production servers.

When git push is done I would want to have `$$BUILD_NUMBER` and `latest` tags on the image.
When we have approval from client I would want to use image tagged as `$$BUILD_NUMBER` or `$$GIT_TAG` to deploy the tested image build into production.

I can do multiple builds ofc but that's slower and it isn't absolutely the same build :).

**Comment by gjtempleton** [comment]
Hey!
You certainly can put multiple tags on an image per build, see the docs here: http://readme.drone.io/plugins/ecr/
This isn't really an issue, future questions like this are probably best addressed (and quickest answered) on the Gitter channel at: https://gitter.im/drone/drone
