### ISSUE TITLE
Create repositories with default policy

### ISSUE THREAD

**Issue by tamasflamich** [drone-plugins/drone-ecr#31]
Hi - We would like to have the ability for setting the policy document for newly created repositories and we are happy to contribute this change.

I imagine to introduce a new env var (e.g `ECR_DEFAULT_POLICY`) that should be [set](http://docs.aws.amazon.com/cli/latest/reference/ecr/set-repository-policy.html) as the policy when the repo does not exists (`ECR_CREATE_REPOSITORY` is true).

One question, can someone explain the following line?
https://github.com/drone-plugins/drone-ecr/blob/master/bin/wrap-drone-docker.sh#L7

**Comment by tboerger** [comment]
This repository is not used anymore, if the issue still applies please open a new issue at [drone-plugins/drone-docker](https://github.com/drone-plugins/drone-docker).
