### ISSUE TITLE
Build args: hide expended values from env from command output

### ISSUE THREAD

**Issue by PuKoren** [drone-plugins/drone-ecr#36]
Hello and thanks for the great project,

I am currently using the plugin to build a container with some build args to fetch private npm modules (npm token), passed with some secrets:

**.drone.yml**
```.drone.yml
  publish:
    image: plugins/ecr
    repo: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    access_key: ${AWS_ACCESS_KEY}
    secret_key: ${AWS_ACCESS_SECRET}
    region: eu-west-1
    build_args: "NPM_TOKEN=${NPM_TOKEN}"
```

**Dockerfile**

```dockerfile
ARG NPM_TOKEN

COPY package.json package.json
COPY yarn.lock yarn.lock

RUN  echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc && \
    yarn install --production && \
    rm ~/.npmrc
```

My issue is with the build log, the token is shown to everyone:

**drone output**
```
+ /usr/local/bin/docker build --pull=true --rm=true -f Dockerfile -t 8c5174965904b863c9e1391638703d6d930bb5b3 --build-arg NPM_TOKEN=plain-text-token-here .
```

Is there a way to hide it? What do you suggest for my use-case?

**Comment by ddho23** [comment]
If you add your NPM_TOKEN to the project as a drone secret with the same name, then the env variable will be defined without showing up in the output. You can also do this for your aws keys if you add  ECR_ACCESS_KEY, ECR_SECRET_KEY as secrets.

http://docs.drone.io/manage-secrets/

**Comment by tboerger** [comment]
This repository is not used anymore, if the issue still applies please open a new issue at [drone-plugins/drone-docker](https://github.com/drone-plugins/drone-docker).
