### ISSUE TITLE
UnrecognizedClientException on PR

### ISSUE THREAD

**Issue by pschuegr** [drone-plugins/drone-ecr#40]
Hi,

I'm seeing some weird behaviour that I don't understand - not clear whether this is a bug or not.

I have a repo that I've just implemented drone-ecr in - my implementation branch `feature/ecr-push` works fine and pushes successfully but the ci run for the pull request into master fails to push to ECR with this message:

`An error occurred (UnrecognizedClientException) when calling the GetAuthorizationToken operation: The security token included in the request is invalid.`

Any thoughts/suggestions?

Thanks!

**Comment by tboerger** [comment]
This repository is not used anymore, if the issue still applies please open a new issue at [drone-plugins/drone-docker](https://github.com/drone-plugins/drone-docker).
