### ISSUE TITLE
use AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY

### ISSUE THREAD

**Issue by bradrydzewski** [drone-plugins/drone-ecr#41]
We should change the name of the secrets of this plugin. I do generally recommend we prefix secrets with the name of the plugin (e.g. ECR_). But in this case, there are well known variable names that we can use instead:

```diff
-ECR_ACCESS_KEY
-ECR_SECRET_KEY
+AWS_ACCESS_KEY_ID
+AWS_SECRET_ACCESS_KEY
```

**Comment by tboerger** [comment]
Maybe both?

**Comment by tboerger** [comment]
This repository is not used anymore, if the issue still applies please open a new issue at [drone-plugins/drone-docker](https://github.com/drone-plugins/drone-docker).
