### ISSUE TITLE
IMPORTANT move to drone-plugins/drone-docker

### ISSUE THREAD

**Issue by bradrydzewski** [drone-plugins/drone-ecr#43]
This should be moved to the main docker plugin repository
https://github.com/drone-plugins/drone-docker/tree/master/cmd/drone-docker-ecr

This wrapper script should be converted to Go when moved
https://github.com/drone-plugins/drone-ecr/blob/master/bin/wrap-drone-docker.sh

This repository is frozen pending its move to the above repository. We will not accept changes or pull requests in preparation to deprecate this repository.

**Comment by tboerger** [comment]
Should be clear with #53
