### ISSUE TITLE
No support for secrets

### ISSUE THREAD

**Issue by omerxx** [drone-plugins/drone-ecr#46]
Hi,

Custom secrets that are passed to the plugin do not get parsed and moved on to the docker plugin.
Can it be added?

**Comment by tboerger** [comment]
What kind of custom secrets? I don't think that this is covered by the docker or ecr plugin at all.

**Comment by omerxx** [comment]
@tboerger Exactly my point.
If I add a secret to `secrets:` list, which is not a specific credential in the documentation, the plugin ignores it.
I would have done it myself but the current code after build and publish to docker hub is not working in production.
There's some kind of authentication problem

**Comment by tboerger** [comment]
Maybe you should take a look at https://github.com/drone-plugins/drone-docker since this plugin currently gets integrated into this repository.

Beside that I don't understand what you want to archive since plugins anyway only listen to specific secrets.

**Comment by omerxx** [comment]
I'd like to expose a specific secret to the build_args
In my case `npm_token`
It's not true that plugins listen to specific secrets. Any entry in `secrets` list is published as an env var to the container with `plugin_` prefix
(http://docs.drone.io/manage-secrets/)

**Comment by tboerger** [comment]
> It's not true that plugins listen to specific secrets. Any entry in secrets list is published as an env var to the container with plugin_ prefix
> (http://docs.drone.io/manage-secrets/)

That's right, but the plugins are still only using a specific amount of secrets/env variables.

**Comment by omerxx** [comment]
I don't understand.
I'd like to have the ability to publish my secrets to `drone-ecr` container and be able to use them internally (in this case with the docker plugin, which this container is wrapping)

**Comment by tboerger** [comment]
This plugin is just executing the docker plugin binary. But AFAIK it's currently not possible to use env variables or secrets for the build args.

**Comment by Sudmota** [comment]
@omerxx I had this question answered [here](https://discourse.drone.io/t/custom-secrets-in-plugins-erc/1051) just yesterday.

All credits to @bradrydzewski .

**Comment by tboerger** [comment]
This repository is not used anymore, if the issue still applies please open a new issue at [drone-plugins/drone-docker](https://github.com/drone-plugins/drone-docker).
