### ISSUE TITLE
Why push is so slow?

### ISSUE THREAD

**Issue by meskis** [drone-plugins/drone-ecr#50]
I've been pushing AWS ECR images from Jenkins and it identifies existing layers and skips it resulting in 15s execution time. For some unknown reason on Drone CI it takes much more time. Any ideas why? Maybe cache?

**Comment by tboerger** [comment]
The default plugin is ephemeral and it's using the docker in docker approach to keep the process really isolated from the host, so it's up to you to use some cache plugin for the docker daemon to speed up the build and push time.

**Comment by meskis** [comment]
Gotcha, thanks! Any suggestions that would work/be set up easily?

**Comment by tboerger** [comment]
There are multiple cache plugins available. Volume, sftp, s3...
