### ISSUE TITLE
Runs docker prune so causes an error when API version is less than 1.25

### ISSUE THREAD

**Issue by ac-hibbert** [drone-plugins/drone-ecr#51]
```
+ /usr/local/bin/docker system prune -f
docker system prune requires API version 1.25, but the Docker daemon API version is 1.24
```

Can this be changed so that it doesn't try to run on lower versions of docker

**Comment by tboerger** [comment]
Is it possible that you used a volume and the host docker socket?

**Comment by tboerger** [comment]
This repository is not used anymore, if the issue still applies please open a new issue at [drone-plugins/drone-docker](https://github.com/drone-plugins/drone-docker).
