### ISSUE TITLE
Can't get to build and run this plugin

### ISSUE THREAD

**Issue by gregory90** [drone-plugins/drone-ecr#6]
If I run image `plugins/drone-ecr` it works flawlessly. However when I try to build plugin myself and run it - it doesn't work.

I get following message from drone:

```
[info] Pulling image gregory90/drone-ecr:latest
time="2016-02-02T14:54:35Z" level=debug msg="Launch config dockerlaunch.Config{Fork:false, CommandName:\"\", DnsConfig:netconf.DnsConfig{Nameservers:[]string(nil), Search:[]string(nil)}, BridgeName:\"\", BridgeAddress:\"\", BridgeMtu:0, CgroupHierarchy:map[string]string(nil), LogFile:\"\", NoLog:false, EmulateSystemd:false, NoFiles:0x0, Environment:[]string(nil)}" 
time="2016-02-02T14:54:35Z" level=debug msg="Mounting devtmpfs /dev devtmpfs " 
time="2016-02-02T14:54:35Z" level=debug msg="Mounting none /dev/pts devpts " 
time="2016-02-02T14:54:35Z" level=debug msg="Mounting shm /dev/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k" 
time="2016-02-02T14:54:35Z" level=debug msg="Mounting mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime" 
time="2016-02-02T14:54:35Z" level=debug msg="Mounting none /proc proc " 
time="2016-02-02T14:54:35Z" level=debug msg="Mounting none /run tmpfs " 
time="2016-02-02T14:54:35Z" level=fatal msg="operation not permitted" 
[info] build failed (exit code 1)
```

I've changed nothing in plugin(except namespace for docker image in Makefile).

**Comment by gregory90** [comment]
Well, it does work locally, so it's probably something on my side. Sorry for the confusion.

**Comment by jeffastorey** [comment]
@gregory90 did you ever get this resolved? I'm having a similar issue with the drone-docker plugin

**Comment by gregory90** [comment]
@jeffastorey No, I didn't. My code was merged, so I wasn't trying to find cause for this anymore.

**Comment by jeffastorey** [comment]
ok, thank you

**Comment by fixe** [comment]
Refs https://github.com/drone/drone-exec/blob/v0.4.2/parser/funcs.go#L150.

**Comment by fixe** [comment]
To test a your fork of this plugin you can workaround [this](https://github.com/drone/drone-exec/blob/v0.4.2/parser/funcs.go#L150) condition with the following steps:
- Activate `trusted` in your repository settings.
- Add `privileged: true` to your `.drone.yml`.

``` yaml
publish:
  ecr:
    image: acme/drone-ecr
    privileged: true
```

**Comment by jeffastorey** [comment]
the privileged flag is what fixed my issue as well. The docker plugin needs to run as privileged, and the default docker plugin automatically does. If you change the namespace of the docker plugin, you need to explicitly add the privileged flag as shown above.

I believe this will be configurable in drone 0.5.
